### ISSUE TITLE
Support for `features` in digitalocean_app spec

### ISSUE THREAD

**Issue by corygibbons** [digitalocean/terraform-provider-digitalocean#1033]
### Is your feature request related to a problem? Please describe.
Trying to [update the buildpack version](https://docs.digitalocean.com/products/app-platform/reference/buildpacks/nodejs/#ubuntu-2204-stack-supporting-nodejs-18) to support node 18 but can't seem to configure it in the [resource](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/app).

### Describe the solution you'd like
Doesn't particularly matter but something similar to env vars could work:
```hcl
resource "digitalocean_app" "foo" {
  spec {
    feature {
      key    = "buildpack-stack"
      value  = "ubuntu-22"
    }
  }
}
```

or

```hcl
resource "digitalocean_app" "foo" {
  spec {
    feature {
      value = "buildpack-stack=ubuntu-22"
    }
  }
}
```

https://docs.digitalocean.com/products/app-platform/reference/app-spec

**Comment by danaelhe** [comment]
Thank you for the suggestion, this should be easy to implement since godo does support features [here](https://github.com/digitalocean/godo/blob/main/apps.gen.go#L473). We've created a ticket in our backlog to get to it as soon as we can. I've also added the "hacktoberfest" label incase someone wanted to take it on for hacktoberfest!

**Comment by T-jegou** [comment]
Hello @danaelhe , I tried to fix this issue, can you take a look? Thanks

**Comment by corygibbons** [comment]
@T-jegou thanks for adding a PR for this 👍
