### ISSUE TITLE
`digitalocean_cdn` resource with custom domain stopped working

### ISSUE THREAD

**Issue by itssimon** [digitalocean/terraform-provider-digitalocean#1086]
# Bug Report

## Describe the bug
Using a `digitalocean_cdn` resource with a custom domain within a Terraform configuration makes all `terraform` commands fail with the following error:

Error: GET https://api.digitalocean.com/v2/certificates/needs-cloudflare-cert: 404 (request "00000000-0000-0000-0000-000000000000") certificate not found

### Affected Resource(s)
- digitalocean_cdn

### Expected Behavior
No errors

### Actual Behavior
Error

### Steps to Reproduce
1. `terraform import terraform_cdn.example 00000000-0000-0000-0000-000000000000`

**Terraform Configuration Files**
```
resource "digitalocean_cdn" "example" {
  origin           = digitalocean_spaces_bucket.example.bucket_domain_name
  custom_domain    = "assets.example.com"
}
```

**Terraform version**
```
Terraform v1.5.4
on darwin_arm64
+ provider registry.terraform.io/digitalocean/digitalocean v2.32.0
```

## Additional context
I've been in touch with the DigitalOcean support team and they have indicated that there has recently been an upgrade to Spaces that enabled users to configure a custom domain for the CDN (with DNS managed elsewhere) without having to provide their own certificate.

I suspect this upgrade has broken the Terraform provider, as now they set the `certificate_id` to `needs-cloudflare-cert`, which doesn't seem to actually be a valid ID.

**Comment by danaelhe** [comment]
Thanks for bringing this to our attention. We've connected with the DO Support team and the DO engineering team that owns this and working this through with them.

What I _think_ is happening is that in the terraform provider, we've deprecated `certificate_id` attribute in favor of `certificate_name` for `digitalocean_cdn` because when the certificate type is lets_encrypt, the certificate ID will change on renewal (after 3 months).

What I think is the problem in the Terraform provider is when `certificate_name` is passed in, we use the name to look up the id and then set that id to `certificate_id`.....hence the `certificate_id` will not be `needs-cloudflare-cert` [here](https://github.com/digitalocean/terraform-provider-digitalocean/blob/main/digitalocean/cdn/resource_cdn.go#L142-L151):
```
	if name, nameOk := d.GetOk("certificate_name"); nameOk {
		certName := name.(string)
		if certName != "" {
			cert, err := certificate.FindCertificateByName(client, certName)
			if err != nil {
				return diag.FromErr(err)
			}

			cdnRequest.CertificateID = cert.ID
		}
```

Still fiddling with it to see if that's it.....but we're looking into it and will push a PR up for a fix when we can.

**Comment by itssimon** [comment]
@danaelhe @andrewsomething Sorry for the late reply. I upgraded the DigitalOcean Terraform provider to 2.34.0, which should include the fix from #1089. But I still receive the same error.

```
$ terraform import digitalocean_cdn.apitally_assets 0cec1b41-0000-0000-0000-bda3e12af860
Error: GET https://api.digitalocean.com/v2/certificates/needs-cloudflare-cert: 404 (request "ef89e86e-0000-0000-0000-3fe9dde0e59f") certificate not found
```

My Terraform configuration for that resource looks like this:

```terraform
resource "digitalocean_cdn" "apitally_assets" {
  origin           = digitalocean_spaces_bucket.apitally_assets.bucket_domain_name
  certificate_name = "needs-cloudflare-cert"
  custom_domain    = "..."
}
```

**Comment by reytech-dev** [comment]
Hey there,
I'm not sure if it contributes to finding the issue but I've received the same error yesterday and stumbled across this GitHub issue.
After enabling the DEBUG loglevel in Terraform I noticed that the Digital Ocean API returns as "**certificate_id**" actually "**needs-cloudflare-cert**":

```2023-12-16T20:33:03.382Z [INFO]  provider.terraform-provider-digitalocean_v2.34.0: 2023/12/16 20:33:03 [DEBUG] DigitalOcean API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Cf-Cache-Status: DYNAMIC
Cf-Ray: 8369b2fadf345702-DUB
Content-Type: application/json; charset=utf-8
Date: Sat, 16 Dec 2023 20:33:03 GMT
Ratelimit-Limit: 5
Ratelimit-Remaining: 4
Ratelimit-Reset: 1702758793
Server: cloudflare
Set-Cookie: __cf_bm=redacted; path=/; expires=Sat, 16-Dec-23 21:03:03 GMT; domain=.digitalocean.com; HttpOnly; Secure; SameSite=None
X-Gateway: Edge-Gateway
X-Request-Id: b9d4b2b1-d738-4132-aaa7-4869f5623c4e
X-Response-From: service

{
 "endpoint": {
  "id": "637d91c9-772a-48b3-abd0-fc18e3fd5306",
  "origin": "redacted.ams3.digitaloceanspaces.com",
  "endpoint": "redacted.ams3.cdn.digitaloceanspaces.com",
  "created_at": "2023-11-04T15:28:32Z",
  "certificate_id": "needs-cloudflare-cert",
  "custom_domain": "redacted",
  "ttl": 3600
 }
}
```

After checking the Digital Ocean UI I could see that my CDN for my Space object was still configured as described in my Terraform plan and linked to my custom domain with custom certificate.
I had to clear the affected resources manually from my Terraform state to be able to destroy my plan. I cleaned the leftovers (Spaces & CDNs) through the Digital Ocean UI.

Today I wanted to apply my resources again with a clean state and no changes in the Terraform definition. I received the following error:

```2023-12-17T14:29:47.672Z [ERROR] vertex "module.space.digitalocean_cdn.sub-cdn[\"docs\"]" error: Error creating CDN: POST https://api.digitalocean.com/v2/cdn/endpoints: 422 (request "dbdb8c17-75b3-4ff4-a7df-98222ca90894") invalid certificate issued by Cloudflare origin CA (type: invalid-cert, retryable: false): invalid certificate issued by Cloudflare origin CA
2023-12-17T14:29:48.264Z [INFO]  provider.terraform-provider-digitalocean_v2.34.0: 2023/12/17 14:29:48 [DEBUG] DigitalOcean API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 422 Unprocessable Entity
Content-Length: 184
Cf-Cache-Status: DYNAMIC
Cf-Ray: 836fdbcb1c7e2a23-CDG
Content-Type: application/json; charset=utf-8
Date: Sun, 17 Dec 2023 14:29:48 GMT
Ratelimit-Limit: 5
Ratelimit-Remaining: 4
Ratelimit-Reset: 1702823379
Server: cloudflare
Set-Cookie: __cf_bm=redacted; path=/; expires=Sun, 17-Dec-23 14:59:48 GMT; domain=.digitalocean.com; HttpOnly; Secure; SameSite=None
X-Gateway: Edge-Gateway
X-Request-Id: bd197641-2616-4a2d-81d0-fbdc99d7800f
X-Response-From: service

{
 "id": "unprocessable_entity",
 "message": "invalid certificate issued by Cloudflare origin CA (type: invalid-cert, retryable: false): invalid certificate issued by Cloudflare origin CA"
}
```

Since I'm not sure if the error from today ("invalid certificate issued by Cloudflare origin CA") is related to the discussed issue, please let me know if I should open a new issue with the newly received error.
I verified that the provided certificate is valid in Cloudflare.

If you need any more information/logs or other details, please let me know.

Regards

**Comment by shuu01** [comment]
In my case I had `let's encrypt` certificate type and the same error. To get rid of the error I had to:

1. Turn off cdn manually from DO web interface.
2. `terraform state rm digitalocean_cdn.name`
3. `terraform apply`
