### ISSUE TITLE
Add Postgres database attributes

### ISSUE THREAD

**Issue by linuxluigi** [digitalocean/terraform-provider-digitalocean#1136]
### Is your feature request related to a problem? Please describe.

I need to configure `work_mem` and `shared_buffers_percentage` for a Postgres cluster. Right now I can only do it via the API, not even with the UI.

### Describe the solution you'd like

Add a way to configure a Postgres cluster like it can be done for MySQL. It looks like the attributes from Postgres are already mapped in [databases.go](https://github.com/digitalocean/terraform-provider-digitalocean/blob/629bb3b8b4717cc2d6e96acf02207009d22790d7/vendor/github.com/digitalocean/godo/databases.go#L512).

### Additional context

I started my [request](https://github.com/pulumi/pulumi-digitalocean/issues/679) at the Pulumi provider, since the Terraform provider mapped already those attributes. 

Thanks for you time! I'm also happy to contribute when I got some hint what to do.

**Comment by danaelhe** [comment]
Hi there,

Thank you for the write up. Good news is that since this is already supported in Godo, this can be supported in our terraform-provider. 

Basically, we'd have to follow the same pattern we did for `digitalocean_database_mysql_config` and `digitalocean_database_redis_config` by creating another resource called `digitalocean_database_postgres_config`. One could reference the code in [resource_database_mysql_config.go](https://github.com/digitalocean/terraform-provider-digitalocean/blob/629bb3b8b4717cc2d6e96acf02207009d22790d7/digitalocean/database/resource_database_mysql_config.go) to create the `digitalocean_database_postgres_config` resource. 

Though our team currently doesn't have the capacity to implement this ourselves within the next few weeks (atleast), we _love_ contributions and will review and merge your PR in a timely manner if you'd like this support sooner!

Thanks,
Dana

**Comment by linuxluigi** [comment]
Thanks for your response. I tried to implemented it as in MySQL.

Here is the PR -> https://github.com/digitalocean/terraform-provider-digitalocean/pull/1139
