### ISSUE TITLE
kubernetes_cluster and kubernetes_node_pool timeout

### ISSUE THREAD

**Issue by paulopontesm** [digitalocean/terraform-provider-digitalocean#329]
Hi there,

We are creating some cluster in digital ocean and it is taking more than the hard coded 20 minutes timeout to create the "kubernetes_cluster". It would be nice if this was configurable.

### Terraform Version

0.12.12

### Affected Resource(s)

- kubernetes_cluster
- kubernetes_node_pool

**Comment by eddiezane** [comment]
@paulopontesm thanks for opening this and apologies that you hit this!

Have you seen this time go down at all since opening? I think you may have run into an incident we were having that caused delays with Droplet creation - https://status.digitalocean.com/incidents/hc7t78cryhph

Thinking out loud here, it looks like Terraform provides us a way to make this timeout configurable but I'm not sure if it's something we need at the moment.

* https://www.terraform.io/docs/configuration/resources.html#operation-timeouts
* https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html

**Comment by Nuxij** [comment]
Please can we have some attention on this issue, it makes the whole thing very unreliable to have a fixed timeout.

The key problem we found is that if the timeout occurs, the state file remains unchanged. This results in subsequent plans failing as "the resource already exists" 🙁
