### ISSUE TITLE
Feature Request : reverse direction of digitalocean_project_resources

### ISSUE THREAD

**Issue by jmrothst** [digitalocean/terraform-provider-digitalocean#461]
### Terraform Version
0.12.28

### Affected Resource(s)
digitalocean_project_resources

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Ability to use digitalocean_droplet (and other resources that work with projects), and specify what project to attach the resource to.

### Actual Behavior
Only way to put a resource in a project is to use digitalocean_project_resources to list all member resources, and thus force all other resources that may not be known about by the current terraform project to be excluded from the project and pushed back to the default.

This causes resources created via other API, or other terraform code base to be kicked out of the digitalocean_project. This behavior causes non-terraform based tooling to become more desirable as they can play nice together.

### Steps to Reproduce
Design

### Important Factoids
N/A

### References
N/A

**Comment by tdyas** [comment]
> Only way to put a resource in a project is to use digitalocean_project_resources to list all member resources, and thus force all other resources that may not be known about by the current terraform project to be excluded from the project and pushed back to the default.

`digitalocean_project_resources` was designed so that you could specify a subset of all of the resources in the project, and it would only manage that subset and not the other resources in the project. A resource should only be put back to the default project if it had been managed by the `digitalocean_project_resources` resources and then removed. See code at https://github.com/digitalocean/terraform-provider-digitalocean/blob/11296f12abe8ecb57aee60f7abb831962b3f4240/digitalocean/resource_digitalocean_project_resources.go#L52-L60.

If this is not working that way, then it is a bug. What happens if you just have `digitalocean_project_resources` with `resources` only set to the droplet in question?

**Comment by tdyas** [comment]
Also are you able to share the Terraform configuration where you see the issue?

**Comment by jmrothst** [comment]
Thanks. Your comments gave me an idea on changing how I was thinking about the problem and solve it. I now have the behavior I wanted by writing a module to do the work and no longer have any issues.
