### ISSUE TITLE
Support for DigitalOcean Marketplace 1-click apps

### ISSUE THREAD

**Issue by devurandom** [digitalocean/terraform-provider-digitalocean#486]
It would be nice if the Terraform DigitalOcean provider would support Marketplace 1-click apps:
* https://cloud.digitalocean.com/marketplace
* https://github.com/digitalocean/marketplace-kubernetes

**Comment by mkell43** [comment]
Wandering through the issues for something else and noticed this. I'm unsure if half of this problem has been fixed since you opened this issue, but the 1-click apps in the marketplace (excluding the Kubernetes ones as far as I could tell) all have image IDs associated with them.

As an example: https://marketplace.digitalocean.com/apps/acra

If you scroll to the bottom there is an example API call to DigitalOcean that includes the image ID to use. 

Outside the scope of this issue and repo, but it would be nice if the image ID for a Marketplace App was someplace more prominent in the DigitalOcean dashboard once logged in.

**Comment by devurandom** [comment]
Thank you for the notification! It seems the marketplace UI has been extended since I filed this request.

I noticed that the Kubernetes DigitalOcean Marketplace Apps seem to be based on public Helm Charts, so I installed them directly instead of using the DigitalOcean provided Marketplace App.

My original issue has been solved, so I am closing this issue.
