### ISSUE TITLE
Question: Updating Floating IP API

### ISSUE THREAD

**Issue by aj-foster** [digitalocean/terraform-provider-digitalocean#623]
Hello there,

I recently received an email from the DigitalOcean team titled _Action Might be Required: Updating Floating IP API_. It describes some API changes starting on 4/26, and that the team "identified your account as one that uses this API endpoint and might be affected."

Presumably my usage of this API is via this Terraform provider. Just wanted to check in and see what the impact might be to users of the provider, and if we should plan on making an update at any particular time.

Thank you all for everything you do. :)

**Comment by andrewsomething** [comment]
Quoting the email for context:

> Starting on April 26 we will begin to roll out an updated version of the Floating IP API that will make the following changes:

> The `private_networking` feature will now be listed under `droplet.features` instead of `region.features`
> `vpc_uuid` was not being populated and will have the correct values now
> The `droplet.type` will be "base" when the droplet is a base image (i.e. Ubuntu, CentOS). The current value is "snapshot"
> The Droplet's networking field will include any private IPs and any floating IPs which are missing from the response today

These changes are around the Droplet object that is included in the floating IP response when attached. We do not anticipate any issues with the Terraform provider due to them. The only values that the provider depends on are will remain the same.

https://github.com/digitalocean/terraform-provider-digitalocean/blob/0c2ad694f600fec38bb8aedea19be68b06c46bcb/digitalocean/resource_digitalocean_floating_ip.go#L141-L142

Hope that helps to clarify the situation!
