### ISSUE TITLE
Add support for price_* attributes with resources other than digitalocean_droplet

### ISSUE THREAD

**Issue by colinwilson** [digitalocean/terraform-provider-digitalocean#634]
### Terraform Version
Terraform v0.15.0

### Affected Resource(s)
- digitalocean_database_cluster
- digitalocean_loadbalancer
- ....

Hi,
The `digitalocean_droplet` resource exports both a `price_monthly` and `price_hourly` attribute.

### Suggestion
It would be useful (if feasible?) to output these two attributes for other billable resources too.

### Use case
My particular use case is to declare an output totalling the price of all billable resources provisioned by `terraform apply`.

**Comment by danaelhe** [comment]
Hi there,

Thanks for surfacing up this important use case. As of now, the "price_monthly" and "price_hourly" are specific attributes to droplets so we wouldn't be able to surface them via other resources just yet. There is tremendous value in the use case you've laid out, and because of that we have relayed it to product management to look closer into it.

Thanks for the feedback!
