### ISSUE TITLE
Supports upload file when creating `digitalocean_custom_image`  Resources.

### ISSUE THREAD

**Issue by VergeDX** [digitalocean/terraform-provider-digitalocean#817]
### Is your feature request related to a problem? Please describe.

I'm using NixOS as deploy, this Linux distribution allow us build work-ready ISO:

[https://nixos.wiki/wiki/Creating_a_NixOS_live_CD](https://nixos.wiki/wiki/Creating_a_NixOS_live_CD)

After build, I got a `nixos.qcow2.gz` file, as Resources `digitalocean_custom_image` in terraform.

But it seems that we can only create custom images through URLs and cannot let terraform to upload local file...

### Describe the solution you'd like

Make a property like `digitalocean` to upload local files.
 
### Describe alternatives you've considered

Manually uploads the custom images, but that can't be integrated into the CI flow...

### Additional context

I also found the API for custom images, which seems not supports upload locally either...

Maybe this is the source of the problem ( ?

[https://docs.digitalocean.com/reference/api/api-reference/#operation/create_custom_image](https://docs.digitalocean.com/reference/api/api-reference/#operation/create_custom_image)

**Comment by andrewsomething** [comment]
Hey @VergeDX! You are correct that the API for custom images only supports importing via a URL. Terraform is limited by that and can not support uploading an image directly. You might want to look into using something like the [DigitalOcean post-processor for Packer](https://www.packer.io/plugins/post-processors/digitalocean) to upload the image, and then you can use it in Terraform to create Droplets. In a lot of ways, Packer is a better tool for the job.

That said, it is possible to do this completely in Terraform by uploading the image to Spaces.

```hcl
resource "digitalocean_spaces_bucket" "image-host" {
  name   = "image-host-001"
  region = "nyc3"
}

resource "digitalocean_spaces_bucket_object" "artifact" {
  region = digitalocean_spaces_bucket.image-host.region
  bucket = digitalocean_spaces_bucket.image-host.name
  acl    = "public-read"
  key    = "nixos.qcow2.gz"
  source = "/path/to/nixos.qcow2.gz"
}

resource "digitalocean_custom_image" "test-image" {
  name    = "test-image-001"
  url     = format("https://%s.%s.digitaloceanspaces.com/%s", digitalocean_spaces_bucket.image-host.name, digitalocean_spaces_bucket.image-host.region, digitalocean_spaces_bucket_object.artifact.key)
  regions = ["nyc3"]
}
```

In fact, that is similar to what Packer does. The main drawback to doing this is that the image is publicly accessible at the URL. After the initial creation, you can delete the copy from Spaces. If you do so you'd need to replace the `format` usage in the `digitalocean_custom_image`'s `url` field with the URL used in order to break the dependency on the Spaces resources.

**Comment by VergeDX** [comment]
Thanks for your reply : )
Actually I thought about a similar solution, which upload images to public cloud storage first. But it seems Spaces in DigitalOcean charged by month, that's not cost-effective for this simple thing : (
