### ISSUE TITLE
Creating certificate returns the name as id instead of the actual id

### ISSUE THREAD

**Issue by the-veloper** [digitalocean/terraform-provider-digitalocean#861]
# Bug Report

---

## Describe the bug
When creating a `digitalocean_certificate` resource I expect that the return result contains the ID of the certificate. Instead it returns the name.

### Affected Resource(s)
- digitalocean_certificate

### Expected Behavior
id_value of the resource matches the id of the resource.

### Actual Behavior
as you can see it returns id_value=e-terraform-auth-service-prod instead of the automatically generated id.
Terraform apply logs:
```
"@level":"info","@message":"digitalocean_certificate.auth-service-cert: Creation complete after 12s [id=le-terraform-auth-service-prod]","@module":"terraform.ui","@timestamp":"2022-08-12T00:38:17.024068Z","hook":{"resource":{"addr":"digitalocean_certificate.auth-service-cert","module":"","resource":"digitalocean_certificate.auth-service-cert","implied_provider":"digitalocean","resource_type":"digitalocean_certificate","resource_name":"auth-service-cert","resource_key":null},"action":"create","id_key":"id","id_value":"le-terraform-auth-service-prod","elapsed_seconds":12},"type":"apply_complete"}
{"@level":"info","@message":"Apply complete! Resources: 1 added, 0 changed, 0 destroyed.","@module":"terraform.ui","@timestamp":"2022-08-12T00:38:17.236605Z","changes":{"add":1,"change":0,"remove":0,"operation":"apply"},"type":"change_summary"}
{"@level":"info","@message":"Outputs: 0","@module":"terraform.ui","@timestamp":"2022-08-12T00:38:17.236699Z","outputs":{},"type":"outputs"}

````

### Steps to Reproduce
certificates.tf:
```
resource "digitalocean_certificate" "auth-service-cert" {
  name    = "le-terraform-auth-service-prod"
  type    = "lets_encrypt"
  domains = ["auth.prod.mydomain.com"]
}
```
run `terraform apply`.
this will succeed, but return the resource name instead of the resource id.

**Comment by andrewsomething** [comment]
Hi @the-veloper,

This is the expected behavior and matches the documentation. Terraform's `id` attribute uses the certificate's name. If you need to access the automatically generated ID, you can do so with the `uuid` attribute.

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/certificate#id

For some more context, Let's Encrypt certificates change their ID when they are renewed. Terraform needs a stable ID that will not change. As the names for certificates have a uniqueness requirement, they can serve this purpose. The names persist across certificate renewals.
